import { useEffect, useMemo, useState } from "react";
import "./FinancePage.css";

const rp = (v) => new Intl.NumberFormat("id-ID", { style:"currency", currency:"IDR", maximumFractionDigits:0 }).format(Number(v)||0);
const today = () => new Date().toISOString().slice(0,10);
const blank = () => ({ category:"OPERASIONAL", description:"", amount:"", expense_date:today(), notes:"" });

export default function FinancePage(){
  const user=window.dayuCurrentUser; const canWrite=["ADMIN","KASIR"].includes(user?.role); const canDelete=user?.role==="ADMIN";
  const [summary,setSummary]=useState(null),[expenses,setExpenses]=useState([]),[query,setQuery]=useState(""),[category,setCategory]=useState("ALL"),[form,setForm]=useState(blank()),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[error,setError]=useState("");
  async function load(){try{const [a,b]=await Promise.all([fetch("/api/business-dashboard-v1"),fetch("/api/expenses-v1")]);const ad=await a.json(),bd=await b.json();if(!a.ok)throw new Error(ad.detail);if(!b.ok)throw new Error(bd.detail);setSummary(ad);setExpenses(bd);}catch(e){setError(e.message)}}
  useEffect(()=>{load();const f=()=>load();window.addEventListener("dayu:orders-changed",f);return()=>window.removeEventListener("dayu:orders-changed",f)},[]);
  const categories=[...new Set(expenses.map(e=>e.category))];
  const filtered=useMemo(()=>expenses.filter(e=>(category==="ALL"||e.category===category)&&(!query||`${e.category} ${e.description} ${e.notes||""} ${e.created_by||""}`.toLowerCase().includes(query.toLowerCase()))),[expenses,query,category]);
  async function save(ev){ev.preventDefault();setError("");const url=editing?`/api/expenses-v1/${editing.id}`:"/api/expenses-v1";const r=await fetch(url,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,amount:Number(form.amount)})});const d=await r.json();if(!r.ok){setError(d.detail||"Gagal menyimpan pengeluaran");return}setOpen(false);setEditing(null);setForm(blank());await load()}
  async function remove(e){if(!confirm(`Hapus pengeluaran ${e.description} sebesar ${rp(e.amount)}?`))return;const r=await fetch(`/api/expenses-v1/${e.id}`,{method:"DELETE"});const d=await r.json();if(!r.ok){setError(d.detail||"Gagal menghapus");return}await load()}
  function edit(e){setEditing(e);setForm({category:e.category,description:e.description,amount:e.amount,expense_date:e.expense_date,notes:e.notes||""});setOpen(true)}
  return <div className="workspace-page finance-page"><header className="workspace-header"><div><h1>Keuangan</h1><p>Ringkasan bisnis dan pengeluaran Dayu Cleanset.</p></div>{canWrite&&<button className="workspace-primary" onClick={()=>{setEditing(null);setForm(blank());setOpen(true)}}>+ Pengeluaran</button>}</header>
    {error&&<div className="workspace-error">{error}</div>}
    {summary&&<><div className="finance-main-stats"><article><span>Pemasukan Hari Ini</span><strong>{rp(summary.income.today)}</strong><small>Bulan ini {rp(summary.income.month)}</small></article><article><span>Pengeluaran Hari Ini</span><strong>{rp(summary.expense.today)}</strong><small>Bulan ini {rp(summary.expense.month)}</small></article><article><span>Laba Bersih Hari Ini</span><strong>{rp(summary.net_profit.today)}</strong><small>Bulan ini {rp(summary.net_profit.month)}</small></article></div><div className="finance-kpis"><div><span>KG Hari Ini</span><strong>{summary.weight_kg.today.toFixed(1)} kg</strong></div><div><span>KG 7 Hari</span><strong>{summary.weight_kg.last_7_days.toFixed(1)} kg</strong></div><div><span>KG All Time</span><strong>{summary.weight_kg.all_time.toFixed(1)} kg</strong></div><div><span>Order Hari Ini</span><strong>{summary.orders.today}</strong></div><div><span>Order Aktif</span><strong>{summary.orders.active}</strong></div><div><span>Belum Lunas</span><strong>{summary.orders.unpaid}</strong></div></div></>}
    <section className="workspace-panel"><div className="finance-filters"><input placeholder="Cari pengeluaran..." value={query} onChange={e=>setQuery(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="ALL">Semua Kategori</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="responsive-table"><table><thead><tr><th>Tanggal</th><th>Kategori</th><th>Keterangan</th><th>Nominal</th><th>Dicatat Oleh</th><th>Aksi</th></tr></thead><tbody>{filtered.length?filtered.map(e=><tr key={e.id}><td>{e.expense_date}</td><td><span className="expense-pill">{e.category}</span></td><td><strong>{e.description}</strong>{e.notes&&<small>{e.notes}</small>}</td><td><strong>{rp(e.amount)}</strong></td><td>{e.created_by||"-"}</td><td><div className="row-actions">{canWrite&&<button onClick={()=>edit(e)}>Edit</button>}{canDelete&&<button className="danger" onClick={()=>remove(e)}>Delete</button>}</div></td></tr>):<tr><td colSpan="6" className="empty-finance">Belum ada pengeluaran.</td></tr>}</tbody></table></div></section>
    {open&&<div className="workspace-modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="workspace-modal" onMouseDown={e=>e.stopPropagation()}><div className="workspace-modal-header"><h2>{editing?"Edit Pengeluaran":"Pengeluaran Baru"}</h2><button onClick={()=>setOpen(false)}>×</button></div><form onSubmit={save}><label>Kategori<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>OPERASIONAL</option><option>DETERJEN</option><option>LISTRIK</option><option>AIR</option><option>GAJI</option><option>MAINTENANCE</option><option>TRANSPORT</option><option>LAINNYA</option></select></label><label>Keterangan<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Nominal (Rp)<input type="number" min="1" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Tanggal<input type="date" required value={form.expense_date} onChange={e=>setForm({...form,expense_date:e.target.value})}/></label><label>Catatan<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="workspace-modal-actions"><button type="button" onClick={()=>setOpen(false)}>Batal</button><button className="workspace-primary">Simpan</button></div></form></div></div>}
  </div>
}
