import { useEffect, useMemo, useState } from "react";
import { OrderDetailTrigger } from "./OrderDetailModal.jsx";
import "./OperationalPage.css";

const STATUSES=["NEW","RECEIVED","WASHING","DRYING","IRONING","READY","DELIVERING","COMPLETE","PICKED_UP"];
const NEXT={NEW:"RECEIVED",RECEIVED:"WASHING",WASHING:"DRYING",DRYING:"IRONING",IRONING:"READY",READY:"COMPLETE",DELIVERING:"COMPLETE"};
const rp=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v)||0);
function fmt(v){return v?new Date(v).toLocaleString("id-ID",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"Tanpa target"}
function deadlineText(o){if(o.deadline_state==="OVERDUE")return `${Math.abs(Math.round(o.minutes_to_target||0))} mnt terlambat`;if(o.deadline_state==="DUE_SOON")return `${Math.max(0,Math.round(o.minutes_to_target||0))} mnt lagi`;if(o.deadline_state==="NO_TARGET")return "Tanpa target";return fmt(o.requested_finish_at)}

export default function OperationalPage(){
 const user=window.dayuCurrentUser;const [data,setData]=useState({summary:{},orders:[]}),[query,setQuery]=useState(""),[filter,setFilter]=useState("ALL"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load({silent=false}={}){if(!silent)setLoading(true);try{const r=await fetch("/api/operational-control-v1");const d=await r.json();if(!r.ok)throw new Error(d.detail||"Gagal mengambil data operasional");setData(d);setError("")}catch(e){setError(e.message)}finally{if(!silent)setLoading(false)}}
 useEffect(()=>{load();const refresh=()=>load({silent:true});window.addEventListener("dayu:orders-changed",refresh);const timer=setInterval(refresh,60000);return()=>{window.removeEventListener("dayu:orders-changed",refresh);clearInterval(timer)}},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return data.orders.filter(o=>{const matchQ=!q||`${o.order_number} ${o.customer} ${o.phone} ${o.hotel_name||""} ${o.room_number||""}`.toLowerCase().includes(q);let matchF=true;if(filter==="OVERDUE")matchF=o.deadline_state==="OVERDUE";if(filter==="DUE_SOON")matchF=o.deadline_state==="DUE_SOON";if(filter==="READY")matchF=o.status==="READY";if(filter==="UNPAID")matchF=o.payment_status!=="PAID";if(filter==="EXPRESS")matchF=o.service_speed==="EXPRESS";return matchQ&&matchF})},[data,query,filter]);
 async function quickStatus(order,status){if(!status)return;try{const r=await fetch(`/api/orders/${order.order_number}/status-v2`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,note:"Update dari Operational Control",changed_by:user?.id||1})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Gagal update status");window.dispatchEvent(new CustomEvent("dayu:orders-changed"));await load({silent:true})}catch(e){setError(e.message)}}
 const s=data.summary||{};
 const cards=[["Aktif",s.active||0,"ALL"],["Terlambat",s.overdue||0,"OVERDUE"],["≤ 3 Jam",s.due_soon||0,"DUE_SOON"],["Siap Pickup",s.ready||0,"READY"],["Belum Lunas",s.unpaid||0,"UNPAID"],["Express",s.express||0,"EXPRESS"]];
 return <div className="workspace-page operational-page"><header className="workspace-header"><div><h1>Operasional</h1><p>Kontrol SLA, prioritas kerja dan order yang perlu tindakan.</p></div><button className="workspace-primary" onClick={()=>load()}>↻ Refresh</button></header>{error&&<div className="workspace-error">{error}</div>}
 <div className="ops-stats">{cards.map(([label,val,key])=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}><span>{label}</span><strong>{val}</strong></button>)}</div>
 <section className="workspace-panel"><div className="ops-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari order, customer, HP, hotel, kamar..."/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">Semua Order Aktif</option><option value="OVERDUE">Terlambat</option><option value="DUE_SOON">Target ≤ 3 Jam</option><option value="READY">Siap Pickup</option><option value="UNPAID">Belum Lunas</option><option value="EXPRESS">Express</option></select></div>
 {loading?<div className="workspace-loading">Memuat operasional...</div>:<div className="responsive-table"><table><thead><tr><th>Prioritas</th><th>Order / Customer</th><th>Lokasi</th><th>Status</th><th>Target Selesai</th><th>Bayar</th><th>Berat</th><th>Aksi Cepat</th></tr></thead><tbody>{filtered.length?filtered.map(o=><tr key={o.order_number} className={`ops-row ${o.deadline_state.toLowerCase()}`}><td><div className="priority-stack">{o.service_speed==="EXPRESS"&&<span className="priority express">EXPRESS</span>}<span className={`priority ${o.deadline_state.toLowerCase()}`}>{o.deadline_state==="OVERDUE"?"TERLAMBAT":o.deadline_state==="DUE_SOON"?"SEGERA":o.deadline_state==="NO_TARGET"?"NO TARGET":"ON TRACK"}</span></div></td><td><OrderDetailTrigger orderNumber={o.order_number}/><small>{o.customer} · {o.phone}</small></td><td>{o.hotel_name||"-"}<small>{o.room_number?`Kamar ${o.room_number}`:""}</small></td><td><span className="ops-status">{o.status}</span></td><td><strong className={o.deadline_state==="OVERDUE"?"deadline-bad":o.deadline_state==="DUE_SOON"?"deadline-warn":""}>{deadlineText(o)}</strong><small>{fmt(o.requested_finish_at)}</small></td><td><span className={`pay-state ${o.payment_status==="PAID"?"paid":"unpaid"}`}>{o.payment_status}</span><small>{rp(o.total)}</small></td><td>{o.total_weight.toFixed(1)} kg</td><td><div className="quick-actions">{NEXT[o.status]&&<button onClick={()=>quickStatus(o,NEXT[o.status])}>→ {NEXT[o.status]}</button>}<select value="" onChange={e=>quickStatus(o,e.target.value)}><option value="">Status...</option>{STATUSES.filter(x=>x!==o.status).map(x=><option key={x}>{x}</option>)}</select></div></td></tr>):<tr><td colSpan="8" className="ops-empty">Tidak ada order pada filter ini.</td></tr>}</tbody></table></div>}</section></div>
}
